spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    username: jpauser
    password: jpauser
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
#        hbm2ddl:
#          auto: create

logging:
  level:
    org.hibernate.SQL: debug    # Logger
    org.hibernate.type: trace   # Show Query Parameter